services:
  backend:
    image: ealen/echo-server:0.5.1
    network_mode: host
    command: --port 8081

  homebrew:
    image: ghcr.io/fabian4/gateway-homebrew-go:0.5.0
    network_mode: host
    volumes:
      - ./gateways/homebrew/config.yaml:/etc/gateway/config.yaml
    depends_on:
      - backend

  envoy:
    image: envoyproxy/envoy:v1.30.1
    network_mode: host
    volumes:
      - ./gateways/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "--service-cluster", "front-proxy"]
    depends_on:
      - backend

  nginx:
    image: nginx:1.26.0
    network_mode: host
    volumes:
      - ./gateways/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  traefik:
    image: traefik:v3.0.1
    network_mode: host
    volumes:
      - ./gateways/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./gateways/traefik/dynamic.yaml:/etc/traefik/dynamic.yaml
    depends_on:
      - backend
